apiVersion: v1
kind: ConfigMap
metadata:
  name: churn-config
data:
  LOG_LEVEL: "INFO"
  MODEL_PATH: artifact/model.joblib
  MLFLOW_TRACKING_URI: http://mlflow.mlops:5000
  MODEL_NAME: churn
  MODEL_ALIAS: champion
