apiVersion: v1
kind: Service
metadata:
  name: churn-service
  labels:
    app: churn
spec:
  type: ClusterIP
  selector:
    app: churn
  ports:
    - name: http
      port: 80
      targetPort: 8000
